import { PERMISSIONS } from './permissions.js';

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  RELEASE_MANAGER: 'release_manager',
  EMAIL_SENDER: 'email_sender',
  VIEWER: 'viewer',
  SPRINT_MANAGER: 'sprint_manager',
  KPI_MANAGER: 'kpi_manager'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS)
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.ADMIN_PANEL_ACCESS,
    PERMISSIONS.USER_MANAGEMENT,
    PERMISSIONS.TEAM_MANAGEMENT,
    PERMISSIONS.RELEASE_VERSIONS_VIEW,
    PERMISSIONS.RELEASE_VERSIONS_EDIT,
    PERMISSIONS.EMAIL_HISTORY_VIEW,
    PERMISSIONS.EMAIL_SEND_GENERIC,
    PERMISSIONS.SPRINT_REPORTS_VIEW,
    PERMISSIONS.KPI_VIEW,
    PERMISSIONS.AI_INSIGHTS_VIEW
  ],
  [ROLES.RELEASE_MANAGER]: [
    PERMISSIONS.RELEASE_VERSIONS_VIEW,
    PERMISSIONS.RELEASE_VERSIONS_EDIT,
    PERMISSIONS.RELEASE_VERSIONS_EMAIL,
    PERMISSIONS.RELEASE_SETUP_MANAGE,
    PERMISSIONS.RELEASE_TRENDS_VIEW,
    PERMISSIONS.AI_INSIGHTS_VIEW,
    PERMISSIONS.CRYSTAL_BALL_ACCESS
  ],
  [ROLES.EMAIL_SENDER]: [
    PERMISSIONS.EMAIL_SEND_GENERIC,
    PERMISSIONS.EMAIL_SEND_RELEASE,
    PERMISSIONS.EMAIL_HISTORY_VIEW
  ],
  [ROLES.SPRINT_MANAGER]: [
    PERMISSIONS.SPRINT_REPORTS_VIEW,
    PERMISSIONS.RELEASE_VERSIONS_VIEW
  ],
  [ROLES.KPI_MANAGER]: [
    PERMISSIONS.KPI_VIEW,
    PERMISSIONS.KPI_MANAGE,
    PERMISSIONS.SPRINT_REPORTS_VIEW
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.RELEASE_VERSIONS_VIEW,
    PERMISSIONS.RELEASE_TRENDS_VIEW,
    PERMISSIONS.KPI_VIEW
  ]
};