/**
 * ReleaseSummaryPanel — display-only.
 *
 * Renders the AI release briefing (health verdict, top blockers, 7-day action
 * list) that was generated by the toolbar "✦ AI Briefing" button in
 * ReleaseVersionSelector. All state lives in ReleaseVersionTab; this component
 * just renders what it receives.
 *
 * Props:
 *   state        'done' | 'error'
 *   summary      markdown-style string from POST /api/ai/release-summary
 *   intelligence bucket counts + metadata from the same endpoint
 *   error        error message string (when state === 'error')
 */

import React from 'react';

const RAG_COLORS = {
  GREEN:  { bg: '#ebfbee', border: '#2f9e44', text: '#2b8a3e', dot: '#2f9e44' },
  YELLOW: { bg: '#fff9db', border: '#f08c00', text: '#e67700', dot: '#f08c00' },
  RED:    { bg: '#fff5f5', border: '#e03131', text: '#c92a2a', dot: '#e03131' },
};

function RagBadge({ verdict }) {
  const col = RAG_COLORS[verdict] || RAG_COLORS.YELLOW;
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: 5,
      padding: '2px 10px', borderRadius: 12,
      background: col.bg, border: `1px solid ${col.border}`,
      color: col.text, fontWeight: 700, fontSize: 12,
    }}>
      <span style={{ width: 7, height: 7, borderRadius: '50%', background: col.dot, flexShrink: 0 }} />
      {verdict}
    </span>
  );
}

function BucketChip({ label, count, color }) {
  if (!count) return null;
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: 4,
      padding: '1px 8px', borderRadius: 10,
      background: color + '18', border: `1px solid ${color}40`,
      color, fontWeight: 600, fontSize: 11,
    }}>
      {count} {label}
    </span>
  );
}

const JIRA_BASE = 'https://jira.nutanix.com';
const TICKET_RE = /\b([A-Z][A-Z0-9]+-\d+)\b/g;

/** Split text on ticket keys and return an array of strings + <a> elements. */
function linkifyTickets(text, baseKey) {
  const parts = [];
  let last = 0;
  let match;
  let i = 0;
  TICKET_RE.lastIndex = 0;
  while ((match = TICKET_RE.exec(text)) !== null) {
    if (match.index > last) parts.push(text.slice(last, match.index));
    const key = match[1];
    parts.push(
      <a
        key={`${baseKey}-${i++}`}
        href={`${JIRA_BASE}/browse/${key}`}
        target="_blank"
        rel="noopener noreferrer"
        style={{ color: '#0052cc', fontWeight: 600, textDecoration: 'none' }}
        onMouseEnter={e => { e.target.style.textDecoration = 'underline'; }}
        onMouseLeave={e => { e.target.style.textDecoration = 'none'; }}
      >
        {key}
      </a>
    );
    last = match.index + match[0].length;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

/** Parse and render the markdown-ish three-section output from NAI */
function SummaryBody({ text }) {
  if (!text) return null;
  const lines = text.split('\n');
  const elements = [];
  let key = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      elements.push(<div key={key++} style={{ height: 6 }} />);
      continue;
    }
    if (trimmed.startsWith('## ')) {
      const heading = trimmed.slice(3);
      const verdictMatch = heading.match(/:\s*(RED|YELLOW|GREEN)$/i);
      elements.push(
        <div key={key++} style={{
          display: 'flex', alignItems: 'center', gap: 8,
          margin: '14px 0 6px', borderBottom: '1px solid #f1f3f5', paddingBottom: 4,
        }}>
          <span style={{ fontWeight: 700, fontSize: 13, color: '#343a40' }}>
            {verdictMatch ? heading.replace(/:\s*(RED|YELLOW|GREEN)$/i, '') : heading}
          </span>
          {verdictMatch && <RagBadge verdict={verdictMatch[1].toUpperCase()} />}
        </div>
      );
    } else if (/^[-•]/.test(trimmed)) {
      elements.push(
        <div key={key++} style={{ display: 'flex', gap: 6, margin: '2px 0', fontSize: 12.5, color: '#343a40', paddingLeft: 4 }}>
          <span style={{ color: '#adb5bd', flexShrink: 0, marginTop: 1 }}>•</span>
          <span>{linkifyTickets(trimmed.slice(1).trim(), `b${key}`)}</span>
        </div>
      );
    } else if (/^\d+\./.test(trimmed)) {
      const num = trimmed.match(/^(\d+)\./)[1];
      elements.push(
        <div key={key++} style={{ display: 'flex', gap: 6, margin: '2px 0', fontSize: 12.5, color: '#343a40', paddingLeft: 4 }}>
          <span style={{ color: '#868e96', flexShrink: 0, fontWeight: 600, minWidth: 16 }}>{num}.</span>
          <span>{linkifyTickets(trimmed.replace(/^\d+\./, '').trim(), `n${key}`)}</span>
        </div>
      );
    } else {
      elements.push(
        <p key={key++} style={{ margin: '3px 0', fontSize: 12.5, color: '#495057', lineHeight: 1.5 }}>{linkifyTickets(trimmed, `p${key}`)}</p>
      );
    }
  }
  return <>{elements}</>;
}

export default function ReleaseSummaryPanel({ state, summary, intelligence, error }) {
  if (!state || state === 'idle') return null;

  const buckets = intelligence?.bucketCounts || {};
  const p0Count = intelligence?.p0BugsCount ?? 0;
  const mustFixCount = intelligence?.mustFixTickets?.length ?? 0;

  return (
    <div style={{
      margin: '0 0 12px',
      border: '1px solid #dee2e6',
      borderRadius: 8,
      background: '#fff',
      overflow: 'hidden',
    }}>
      {/* Header — neutral, no RAG colouring here. RAG badge lives inside the body heading. */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '8px 14px',
        background: '#f8f9fa',
        borderBottom: '1px solid #e9ecef',
        flexWrap: 'wrap', gap: 6,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
          <span style={{ fontSize: 13, fontWeight: 600, color: '#343a40' }}>AI Release Briefing</span>
          {state === 'loading' && (
            <span style={{ fontSize: 11, color: '#868e96', display: 'flex', alignItems: 'center', gap: 5 }}>
              <span style={{
                display: 'inline-block', width: 10, height: 10,
                border: '1.5px solid #dee2e6', borderTopColor: '#845ef7',
                borderRadius: '50%', animation: 'rsp-spin 0.8s linear infinite',
              }} />
              Analysing {intelligence?.totalFeatures ? `${intelligence.totalFeatures} features` : 'all committed features'} …
              <style>{`@keyframes rsp-spin { to { transform: rotate(360deg); } }`}</style>
            </span>
          )}
          {state === 'done' && intelligence && (
            <span style={{ fontSize: 11, color: '#868e96' }}>
              {intelligence.totalFeatures} features
              {p0Count > 0 && <span style={{ color: '#c92a2a', fontWeight: 700 }}> · {p0Count} P0s</span>}
              {mustFixCount > 0 && <span style={{ color: '#e67700', fontWeight: 700 }}> · {mustFixCount} must-fix</span>}
            </span>
          )}
        </div>
        {state === 'done' && (
          <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
            <BucketChip label="gate-lagging" count={buckets['gate-lagging']} color="#c92a2a" />
            <BucketChip label="blocked"      count={buckets['blocked']}      color="#e67700" />
            <BucketChip label="compliance"   count={buckets['compliance']}   color="#9c36b5" />
            <BucketChip label="dark"         count={buckets['dark']}         color="#868e96" />
          </div>
        )}
      </div>

      {/* Body */}
      {state === 'loading' && (
        <div style={{ padding: '16px', fontSize: 12.5, color: '#868e96' }}>
          Fetching P0 bugs, must-fix tickets, and gate status for all committed features — 15–30 s…
        </div>
      )}
      {state === 'error' && (
        <div style={{ padding: '10px 14px', fontSize: 12.5, color: '#c92a2a', background: '#fff5f5' }}>
          {error || 'Generation failed — click ✦ Re-brief in the toolbar to retry.'}
        </div>
      )}
      {state === 'done' && summary && (
        <div style={{ padding: '8px 16px 14px' }}>
          <SummaryBody text={summary} />
          {intelligence?.generatedAt && (
            <div style={{
              marginTop: 10, fontSize: 11, color: '#adb5bd',
              borderTop: '1px solid #f1f3f5', paddingTop: 6,
            }}>
              Generated {new Date(intelligence.generatedAt).toLocaleString()}
              {' · '}gate-lagging: {buckets['gate-lagging'] ?? 0}
              {' · '}P0 blockers: {p0Count}
              {' · '}must-fix open: {mustFixCount}
            </div>
          )}
        </div>
      )}
      {state === 'done' && !summary && (
        <div style={{ padding: '10px 14px', fontSize: 12.5, color: '#868e96' }}>
          No summary was returned. Click ✦ Re-brief in the toolbar to try again.
        </div>
      )}
    </div>
  );
}
